#!/bin/sh
#

cc -Wall -D_GNU_SOURCE -o mapad *.c -lpthread
#/home/matt/openwrt/kamikaze/staging_dir/toolchain-mipsel_gcc-4.1.2_uClibc-0.9.30.1/usr/bin/mipsel-openwrt-linux-uclibc-gcc -Wall -D_GNU_SOURCE -o mapad *.c -lpthread
